import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <head>
      <script src="https://kit.fontawesome.com/4b53cf44c7.js" crossorigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        
        {children}
        
        </body>
    </html>
  )
}
